name: Training Model

on:
  push:
    branches:
      - master

env:
  MLFLOW_TRACKING_URI: "https://dagshub.com/RizkiYanuar-Tech/Workflow-CI.mlflow"
  MLFLOW_TRACKING_USERNAME: "RizkiYanuar-Tech"
  DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_USER_TOKEN }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_USER_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
    
    # Setup environment
      - name: Set up python 3.12
        uses: actions/setup-python@v4
        with: 
          python-version: "3.12"

    # Install dependencies
      - name: Install Dependencies
        run: |
          pip install mlflow dagshub scikit-learn python-dotenv pandas

      - name: Run Modelling.py
        run: |
          mlflow run MLProject --env-manager=local

      - name: Github Release & Upload Artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }} # Versi Dinamis
          name: "Model rilis v1.0.${{ github.run_number }}"
          files: |
            *.pkl # Simpan file model fisik ke release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Model
        run: |
          # Ambil model berdasarkan nama dan versi terakhir di dagshub
          mlflow models build-docker --model-uri "models:/Model_Churn/latest" --name 'dicoding-smsml'

      - name: Login ke Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Tag Docker Image
        run: |
          docker tag dicoding-smsml ${{secrets.DOCKER_HUB_USERNAME}}/dicoding-smsml:latest

      - name: Push docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/dicoding-smsml:latest
          